services:
  redis:
    image: "redis"
    container_name: "redis"
    ports:
      - "6379:6379"
  jeager:
    image: "jaegertracing/jaeger:2.1.0"
    container_name: "jeager"
    ports:
      - "4317:4317" #gRPC exporter
      - "16686:16686" #UI
    environment:
      COLLECTOR_OTLP_ENABLED: true